version: "2"
run:
    timeout: 3m
linters:
    default: standard
    enable:
      - goconst
      - gocyclo
      - gosec
      - staticcheck
      - nilerr
      - prealloc
      - revive
      - staticcheck
      - unconvert
      - unused
      - whitespace
      - zerologlint
    settings:
        gocyclo:
            min-complexity: 13
        goconst:
            min-occurrences: 2
    exclusions:
        paths:
          - export_test.go
          - consumer_iface.go
        rules:
        # Exclude gosec from running on tests files.
        - path: _test\.go
          linters:
            - goconst
            - gosec
            - revive
        - path: mig_(.+)\.go
          linters:
            - revive
          text: "unused-parameter: parameter 'driver'"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - export_test.go
      - consumer_iface.go
