{
 "title": "CCX Notification Writer",
 "description": "Dashboard for CCX notification writer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  { "title": "CCX Notification Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "Incoming metrics",
   "type": "timeseries",
   "description": "Metrics for operations related to consumed messages handling",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_writer_check_last_checked_timestamp{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_check_schema_version{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_consumed_messages{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_marshal_report{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_parse_incoming_message{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Outgoing metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_writer_shrink_report{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_marshal_report{namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum(rate(ccx_notification_writer_stored_messages{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Bytes stored per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_writer_stored_bytes{namespace=\"$namespace\"}[1m]))"
    }
   ]
  }
 ]
}