name: BDD tests

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  bdd:
    name: BDD tests
    uses: RedHatInsights/processing-tools/.github/workflows/bdd.yaml@master
    with:
      service: notification-writer
      use_postgres: true
